### ISSUE TITLE
The super constructor to "inherits" must not ' +

### ISSUE THREAD

**Issue by amoharir** [sstur/nodeftpd#124]
I am getting below error while compiling test.js

`util.js:965
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:965:11)
    at Object.<anonymous> (D:\Personal\examples\node_modules\ft
pd\lib\ftpd.js:67:6)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Personal\examples\test.js:1:74)`

**Comment by mk-pmb** [comment]
What do you mean with "compile"? Usually node (or rather, v8 on node's behalf) does all compilation on the fly at runtime.
Did you use a shell to start nodejs?
Which shell command did you use for that?
Which directory was the shell in when you issued the command?
It looks like you've installed nodeftpd in
`D:\Personal\examples\node_modules\ftpd` and ran
`D:\Personal\examples\test.js` which is outside the scope of this repo. What's in that outer `test.js`?

**Comment by amoharir** [comment]
I am using a window based nodeJS and I have stored all my applications in `D:\Personal\examples`

I tried compiling test.js inside the `D:\Personal\examples\node_modules/ftpd`  as well as `D:\Personal\examples\` and both yields me the same result as mentioned in my above post.

Running `node` -p `"require('ftpd/package.json').version"` gives me output as `0.2.1`

**Comment by Bizarrus** [comment]
Same problem with Node `v7.4.0`

**Comment by mk-pmb** [comment]
I tried to check it but the file where the error occurs:

> at Object. (…\ftpd\lib\ftpd.js:67:6)

no longer exists in the current version, so all I can suggest for now is to try with the latest master from this github repo. The version in package.json should be 0.2.14 then.

**Comment by Bizarrus** [comment]
Fixed my local version easily:
Replace the `process.EventEmitter` (think it was `process`? Currently dont have the source) to `events` (from `require('events')`) - 3 replacements on ftpd.js solves the Problem.

**Comment by mk-pmb** [comment]
Thanks for sharing how to repair the old version!

**Comment by ilyatauu** [comment]
thanks a lot for sharing, had same problem either. Version 0.2.15 on windows and node 7.3.0

**Comment by wayofthefuture** [comment]
On Node 7.7 with 0.2.15 having same problem

**Comment by wayofthefuture** [comment]
Solved by installing from GitHub:

> npm i https://github.com/sstur/nodeftpd.git --save

**Comment by svrooij** [comment]
The package structure is really broken, with this many forks and people doing things about it.... Thanks @wayofthefuture for the solution!

**Comment by sdsondhi** [comment]
Thanks @Bizarrus : your work around worked for the present instance. Please submit the edit as an addition to the present code for ftpd since we cannot use customized GPL software for running proprietary apps on node AND its modules if we alter the code. Alteration of the code implies voiding the licensing and makes the code users and editors using the altered ftpd liable for legal punishment unless they submit the code suggestion back to the open source repo with a complete use-case.

Thanks @wayofthefuture for the alternate repository. I was looking for a confirmation that the license being used is the same old GPL so that I may include it as a standard dependency.

No thanks to the node team for ensuring that modules like ftpd which were supported in their previous 6.x LTS are now almost pushed to obsolescence because of such rewrites and their latest LTS being of the 8.x Series.

**Comment by harishmahajan** [comment]
npm i https://github.com/sstur/nodeftpd.git --save

still not works for me

**Comment by Bizarrus** [comment]
@harishmahajan read the comments.

**Comment by harishmahajan** [comment]
@Bizarrus 
Fixed my local version easily:
Replace the process.EventEmitter (think it was process? Currently dont have the source) to events (from require('events')) - 3 replacements on ftpd.js solves the Problem.

==> but in which file ftpd.js ?? 

       but my ftpd file contains, below 3 lines.
       var Constants = require('./lib/Constants');
       exports.FtpServer = require('./lib/FtpServer');
       exports.LOG_LEVELS = Constants.LOG_LEVELS;

**Comment by sdsondhi** [comment]
@harishmahajan : as per the comment in the git, the ftpd.js is now a stub. Code has also been updated to remove the deprecated process.EventEmitter issue. If the problem persists please post a detailed error report. Maybe your problem needs to be addressed in another/ seperate thread.

Please keep in mind that the versions of node before 6.x require the earlier version of ftpd while recent LTS of 8.x will work with the new one as the process.EventEmiiter was deprecated in the 7.x versions which never hit 
LTS.

**Comment by Amoud94** [comment]
guys i'm having this problem : 
[user@MacBook-Pro NodeJS]$ node fileevent.js   
util.js:957
throw new TypeError('The super constructor to "inherits" must not ' +
^

TypeError: The super constructor to "inherits" must not be null or undefined
at Object.exports.inherits (util.js:957:11)
at Object.<anonymous> (/Users/user/Documents/NodeJS/fileevent.js:15:6)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:389:7)
at startup (bootstrap_node.js:149:9)`

**Comment by Bizarrus** [comment]
Please try to fix the issue with above solutions...

**Comment by pablokvitca** [comment]
Still happens on version 0.2.15 (which is the latest on npm, though the version number on here is 0.2.14, which has me really confused)
